---
- name: Create GKE Cluster
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create a GKE cluster
      google.cloud.gcp_container_cluster:
        name: gke-cluster01
        initial_node_count: 2
        node_config:
          machine_type: n2-standard-4
          disk_size_gb: 500
        location: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: absent
